CREATE OR REPLACE EXTERNAL TABLE `kleague-482106.Kleague_db.measurements`
(
  Test_ID STRING,
  Player_ID INTEGER,
  Date DATE,
  Under STRING,
  Team STRING,
  Player STRING,
  Year INTEGER,
  Birth_Year STRING,
  Birth_Date DATE,
  Grade STRING,
  Position STRING,
  Days INTEGER,
  Age FLOAT64,
  Height FLOAT64,
  Weight FLOAT64,
  Sitting FLOAT64,
  Maturity_Offset FLOAT64,
  APHV FLOAT64,
  Maturity STRING,
  -- 아래부터는 데이터 오염 가능성이 높은 측정값들입니다. 
  -- 안전하게 전부 STRING으로 지정합니다. (나중에 필요하면 CAST로 숫자로 바꿀 수 있음)
  HamECC_L_N_ STRING,
  HamECC_R_N_ STRING,
  HipAdd_L_N_ STRING,
  HipAdd_R_N_ STRING,
  HipAbd_L_N_ STRING,
  HipAbd_R_N_ STRING,
  ShoulderIR_L_N_ STRING,
  ShoulderIR_R_N_ STRING,
  ShoulderER_L_N_ STRING,
  ShoulderER_R_N_ STRING,
  _5m_sec_ STRING,
  _10m_sec_ STRING,
  _30m_sec_ STRING,
  COD_sec_ STRING,
  COD_ball_sec_ STRING,
  CMJ_Height_cm_ STRING,
  CMJ_TakeoffConcentricPeakForce_N_ STRING,
  CMRJ_RSI STRING,
  SquatJ_Height_cm_ STRING,
  IMTP_N_ STRING,
  EUR_CMJ_SquatJ_ STRING,
  DSI_CMJ_IMTP_ STRING,
  Ham STRING,
  Add STRING,
  Abd STRING,
  Flex STRING,
  Strength_Sum STRING,
  APHV_Point_ STRING,
  HamECC_L_Point_ STRING,
  HamECC_R_Point_ STRING,
  HipAdd_L_Point_ STRING,
  HipAdd_R_Point_ STRING,
  HipAbd_L_Point_ STRING,
  HipAbd_R_Point_ STRING,
  ShoulderIR_L_Point_ STRING,
  ShoulderIR_R_Point_ STRING,
  ShoulderER_L_Point_ STRING,
  ShoulderER_R_Point_ STRING,
  _5m_sec__Point_ STRING,
  _10m_sec__Point_ STRING,
  _30m_sec__Point_ STRING,
  COD_Point_ STRING,
  COD_ball_Point_ STRING,
  CMJ_Height_Point_ STRING
)
OPTIONS (
  format = 'GOOGLE_SHEETS',
  uris = ['https://docs.google.com/spreadsheets/d/1q5dhuIphFnSpHvF7aUxxlaq5baMKEGWAFWazhnDusoY/edit?gid=1218661279#gid=1218661279'],
  skip_leading_rows = 1
);
